/**
 * Scrappy - File Generator: DOCX
 * Company: Cosmic
 *
 * Uses the `docx` npm package to produce real Word documents.
 */

import path from 'path';
import {
  Document, Paragraph, TextRun, HeadingLevel,
  AlignmentType, Packer, BorderStyle, Table,
  TableRow, TableCell, WidthType,
} from 'docx';
import fs from 'fs';
import { getOutputDir, ensureScrappyDirs } from '../../utils/paths';

export interface DocxOptions {
  title: string;
  content: string;       // plain text or markdown-lite
  filename?: string;
  author?: string;
}

/**
 * Parse very simple markdown into docx Paragraphs.
 * Handles: # headings, ## sub-headings, - bullets, blank lines.
 */
function parseMarkdown(text: string): Paragraph[] {
  const paragraphs: Paragraph[] = [];
  const lines = text.split('\n');

  for (const raw of lines) {
    const line = raw.trimEnd();

    if (/^###\s/.test(line)) {
      paragraphs.push(new Paragraph({
        text: line.replace(/^###\s/, ''),
        heading: HeadingLevel.HEADING_3,
      }));
    } else if (/^##\s/.test(line)) {
      paragraphs.push(new Paragraph({
        text: line.replace(/^##\s/, ''),
        heading: HeadingLevel.HEADING_2,
      }));
    } else if (/^#\s/.test(line)) {
      paragraphs.push(new Paragraph({
        text: line.replace(/^#\s/, ''),
        heading: HeadingLevel.HEADING_1,
      }));
    } else if (/^[-*]\s/.test(line)) {
      paragraphs.push(new Paragraph({
        text: line.replace(/^[-*]\s/, ''),
        bullet: { level: 0 },
      }));
    } else if (line.trim() === '') {
      paragraphs.push(new Paragraph({ text: '' }));
    } else {
      // Handle **bold** inline
      const boldParts = line.split(/\*\*(.+?)\*\*/g);
      const runs: TextRun[] = boldParts.map((part, i) =>
        new TextRun({ text: part, bold: i % 2 === 1 })
      );
      paragraphs.push(new Paragraph({ children: runs }));
    }
  }

  return paragraphs;
}

/**
 * Create a .docx file from content.
 * Returns the output file path.
 */
export async function createDocx(options: DocxOptions): Promise<string> {
  ensureScrappyDirs();

  const filename = options.filename
    ? (options.filename.endsWith('.docx') ? options.filename : options.filename + '.docx')
    : `scrappy_${Date.now()}.docx`;

  const outputPath = path.join(getOutputDir(), filename);

  const titleParagraph = new Paragraph({
    children: [new TextRun({ text: options.title, bold: true, size: 36 })],
    heading: HeadingLevel.TITLE,
    alignment: AlignmentType.CENTER,
    spacing: { after: 400 },
  });

  const metaParagraph = new Paragraph({
    children: [
      new TextRun({
        text: `Generated by Scrappy — Cosmic CLI Agent | ${new Date().toLocaleString()}`,
        italics: true,
        color: '888888',
        size: 18,
      }),
    ],
    alignment: AlignmentType.CENTER,
    spacing: { after: 600 },
  });

  const bodyParagraphs = parseMarkdown(options.content);

  const doc = new Document({
    creator: options.author ?? 'Scrappy — Cosmic',
    title: options.title,
    description: 'Generated by Scrappy CLI',
    sections: [{
      properties: {},
      children: [titleParagraph, metaParagraph, ...bodyParagraphs],
    }],
  });

  const buffer = await Packer.toBuffer(doc);
  fs.writeFileSync(outputPath, buffer);
  return outputPath;
}
