/**
 * Scrappy - File Generator: Excel (.xlsx)
 * Company: Cosmic
 *
 * Uses `exceljs` to produce real Excel workbooks.
 */

import path from 'path';
import ExcelJS from 'exceljs';
import { getOutputDir, ensureScrappyDirs } from '../../utils/paths';

export interface ExcelOptions {
  sheetName?: string;
  rows: Record<string, any>[];   // Array of objects → auto-detect columns
  filename?: string;
  title?: string;
}

/**
 * Create a styled .xlsx file.
 * Returns the output file path.
 */
export async function createExcel(options: ExcelOptions): Promise<string> {
  ensureScrappyDirs();

  const filename = options.filename
    ? (options.filename.endsWith('.xlsx') ? options.filename : options.filename + '.xlsx')
    : `scrappy_${Date.now()}.xlsx`;

  const outputPath = path.join(getOutputDir(), filename);

  const wb = new ExcelJS.Workbook();
  wb.creator = 'Scrappy — Cosmic CLI Agent';
  wb.created = new Date();

  const sheetName = options.sheetName ?? 'Scrappy Data';
  const ws = wb.addWorksheet(sheetName);

  // Derive column headers from first row's keys
  const headers = options.rows.length > 0 ? Object.keys(options.rows[0]) : [];

  // Define columns with styling
  ws.columns = headers.map(h => ({
    header: h,
    key: h,
    width: Math.max(h.length + 4, 18),
  }));

  // Style header row
  const headerRow = ws.getRow(1);
  headerRow.eachCell(cell => {
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF3B82F6' },   // Cosmic blue
    };
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 12 };
    cell.alignment = { vertical: 'middle', horizontal: 'center' };
    cell.border = {
      top:    { style: 'thin', color: { argb: 'FF1E40AF' } },
      bottom: { style: 'thin', color: { argb: 'FF1E40AF' } },
      left:   { style: 'thin', color: { argb: 'FF1E40AF' } },
      right:  { style: 'thin', color: { argb: 'FF1E40AF' } },
    };
  });
  headerRow.height = 24;

  // Add data rows with alternating background
  options.rows.forEach((rowData, i) => {
    const row = ws.addRow(rowData);
    row.eachCell(cell => {
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: i % 2 === 0 ? 'FFFAFAFA' : 'FFEFF6FF' },
      };
      cell.border = {
        top:    { style: 'hair', color: { argb: 'FFD1D5DB' } },
        bottom: { style: 'hair', color: { argb: 'FFD1D5DB' } },
        left:   { style: 'hair', color: { argb: 'FFD1D5DB' } },
        right:  { style: 'hair', color: { argb: 'FFD1D5DB' } },
      };
    });
  });

  // Add a metadata footer
  const lastRow = ws.lastRow?.number ?? 1;
  ws.getCell(`A${lastRow + 2}`).value =
    `Generated by Scrappy — Cosmic CLI Agent | ${new Date().toLocaleString()}`;
  ws.getCell(`A${lastRow + 2}`).font = { italic: true, color: { argb: 'FF9CA3AF' }, size: 10 };

  await wb.xlsx.writeFile(outputPath);
  return outputPath;
}

/**
 * Convert a scraped table (headers + rows) to Excel.
 */
export async function tableToExcel(
  headers: string[],
  tableRows: string[][],
  filename?: string
): Promise<string> {
  const rows: Record<string, any>[] = tableRows.map(r => {
    const obj: Record<string, any> = {};
    headers.forEach((h, i) => { obj[h] = r[i] ?? ''; });
    return obj;
  });
  return createExcel({ rows, filename });
}
