/**
 * Scrappy - File Generator: README.md
 * Company: Cosmic
 */

import fs from 'fs';
import path from 'path';
import { getOutputDir, ensureScrappyDirs } from '../../utils/paths';

export interface ReadmeOptions {
  title: string;
  description?: string;
  content: string;
  filename?: string;
}

/**
 * Generate a README.md file from structured content.
 * Saved to ~/.scrappy/output/<filename>.md
 */
export function createReadme(options: ReadmeOptions): string {
  ensureScrappyDirs();

  const filename = options.filename
    ? (options.filename.endsWith('.md') ? options.filename : options.filename + '.md')
    : 'README.md';

  const outputPath = path.join(getOutputDir(), filename);

  const md = `# ${options.title}

${options.description ? `> ${options.description}\n` : ''}
${options.content}

---
*Generated by Scrappy — Cosmic CLI Agent*  
*${new Date().toLocaleString()}*
`;

  fs.writeFileSync(outputPath, md, 'utf-8');
  return outputPath;
}

/**
 * Generate README from plain text content (LLM output).
 */
export function createReadmeFromText(rawContent: string, filename?: string): string {
  // Try to extract title from first heading
  const titleMatch = rawContent.match(/^#\s+(.+)$/m);
  const title = titleMatch?.[1] ?? 'Document';

  return createReadme({
    title,
    content: rawContent,
    filename: filename ?? 'README.md',
  });
}
