/**
 * Scrappy CLI - Research Command Handler
 * Company: Cosmic
 *
 * Handles `scrappy research "<query>"` — boots the ResearchEngine
 * and renders a beautiful terminal result summary.
 */

import { ResearchEngine } from '../core/research';
import { c, printBox, printDivider, startResponse, endResponse, printResponseLine } from './ui';

export async function runResearch(query: string, folderName?: string): Promise<void> {
  startResponse(true);
  printResponseLine(c.whiteBold(`🌌 Full Research Mode — Cosmic Intelligence`));
  printResponseLine(c.gray('One prompt. Complete research. Export anywhere.'));
  printResponseLine('─'.repeat(50));

  const engine = new ResearchEngine(query, folderName);

  try {
    const result = await engine.run();

    // ── Final report card ──────────────────────────────────────────────────
    console.log();
    printDivider();
    printResponseLine(c.blueBold('  📊 RESEARCH COMPLETE') + c.gray(` — ${result.sources.length} sources analysed`));
    printDivider();

    // Summary box
    const summaryLines = result.summary
      .split('\n\n')
      .slice(0, 3)
      .map(l => l.trim())
      .filter(Boolean)
      .map(l => c.white(l.slice(0, 100) + '...'));

    printBox('Summary', summaryLines);

    // Key insights
    if (result.keyInsights.length > 0) {
      printResponseLine('');
      printResponseLine(c.blueBold('  🔍 Key Insights'));
      for (const insight of result.keyInsights.slice(0, 7)) {
        printResponseLine(c.green('    • ') + c.white(insight));
      }
    }

    // Output files
    printResponseLine(c.blueBold('📁 Output Files'));
    printResponseLine(c.green('  📄 README.md    : ') + c.white(result.markdownReport));
    printResponseLine(c.green('  📊 report.docx  : ') + c.white(result.docxPath));
    if (result.excelPath) {
      printResponseLine(c.green('  📈 data.xlsx    : ') + c.white(result.excelPath));
    }

    printResponseLine('');
    printResponseLine(c.green('✅ All files saved to: ') + c.whiteBold(result.folderPath));
    printResponseLine(c.gray(`Report generated by Scrappy — Cosmic CLI`));
    
    endResponse();

  } catch (err: any) {
    printResponseLine('');
    printResponseLine(c.red(`  ✗ Research failed: ${err?.message ?? String(err)}`));
    endResponse();
    process.exit(1);
  }
}
