import YahooFinance from 'yahoo-finance2';
const yahooFinance = new YahooFinance({ suppressNotices: ['yahooSurvey'] });
import path from 'path';
import fs from 'fs';
import { c, printBox, printDivider, startSpinner, stopSpinner, sleep, startResponse, endResponse, printResponseLine, getLayoutWidth } from './ui';
import stripAnsi from 'strip-ansi';
import ExcelJS from 'exceljs';
import { Document, Paragraph, TextRun, HeadingLevel, AlignmentType, Packer } from 'docx';
import { getLLM } from '../agent/llm';

export async function runStock(ticker: string, options: { excel?: boolean, docx?: boolean, report?: boolean }) {
  startResponse(true);
  printResponseLine(c.whiteBold(`📈 Scrappy Stock Market Agent — ${ticker.toUpperCase()}`));
  printResponseLine(c.gray('Analyzing global financials and recent market shifts...'));
  console.log(c.blue('║') + '─'.repeat(getLayoutWidth() - 2) + c.blue('║'));

  try {
    const symbol = ticker.toUpperCase();

    const progress = async (msg: string, percent: number) => {
      const width = getLayoutWidth();
      const barLength = Math.max(10, Math.floor(width / 4));
      const filledLength = Math.round((barLength * percent) / 100);
      const bar = '■'.repeat(filledLength) + '□'.repeat(barLength - filledLength);
      const output = `${c.blue(`[${bar}]`)} ${c.gray(msg)}`;
      const stripped = stripAnsi(output);
      const padding = Math.max(0, width - 4 - stripped.length);
      process.stdout.write(`\r${c.blue('║ ')}${output}${' '.repeat(padding)}${c.blue(' ║')}`);
      await sleep(200);
      if (percent === 100) console.log(); 
    };

    await progress('Fetching Financial Info...', 10);
    const quote: any = await yahooFinance.quote(symbol);
    const modules: any = await yahooFinance.quoteSummary(symbol, { modules: ['assetProfile', 'financialData', 'defaultKeyStatistics'] });

    await progress('Fetching Latest News...', 40);
    const news: any = await yahooFinance.search(symbol, { newsCount: 5 });

    await progress('Analyzing data with LLM...', 70);
    
    // Fallback if modules aren't fully available
    const curPrice = quote.regularMarketPrice ?? 'N/A';
    const currency = quote.currency ?? 'USD';
    const profile = modules.assetProfile ?? {};
    const companyName = quote.longName || quote.shortName || symbol;
    const summary = profile.longBusinessSummary || 'No summary available.';

    const newsText = news.news.map(n => `- ${n.title}`).join('\n');

    const prompt = `You are an expert financial analyst. Please summarize the following company data for ${companyName} (${symbol}).
Company Summary: ${summary.substring(0, 1000)}...
Current Price: ${curPrice} ${currency}
Recent News:
${newsText}

Provide:
1. Executive Summary (1-2 paragraphs)
2. 5 Bullet Point Key Takeaways on recent status and what the firm does.

Format:
[SUMMARY]
...
[/SUMMARY]
[TAKEAWAYS]
- ...
[/TAKEAWAYS]
`;
    const llm = getLLM();
    const rawAnalysis = await llm.complete(prompt);

    const summaryMatch = rawAnalysis.match(/\[SUMMARY\]([\s\S]*?)\[\/SUMMARY\]/);
    const takeawaysMatch = rawAnalysis.match(/\[TAKEAWAYS\]([\s\S]*?)\[\/TAKEAWAYS\]/);
    
    const analysisSummary = summaryMatch ? summaryMatch[1].trim() : "Analysis failed to format.";
    const analysisTakeaways = takeawaysMatch ? takeawaysMatch[1].split('\n').filter(l=>l.trim().startsWith('-')).map(l=>l.replace(/^-\s*/, '').trim()) : [];

    await progress('Generating Exports...', 90);

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const folder = process.cwd();
    
    // Markdown
    const mdContent = `# Stock Report: ${companyName} (${symbol})
Generated by Scrappy · ${new Date().toLocaleString()}

## Financial Overview
- **Price:** ${curPrice} ${currency}
- **52 Week High:** ${quote.fiftyTwoWeekHigh ?? 'N/A'}
- **52 Week Low:** ${quote.fiftyTwoWeekLow ?? 'N/A'}
- **Volume:** ${quote.regularMarketVolume ?? 'N/A'}
- **Market Cap:** ${quote.marketCap ?? 'N/A'}
- **Trailing P/E:** ${quote.trailingPE ?? 'N/A'}

## Executive Summary
${analysisSummary}

## Key Takeaways
${analysisTakeaways.map(t => `- ${t}`).join('\n')}

## Recent News
${news.news.map((n: any) => `- [${n.title}](${n.link})`).join('\n')}
`;
    const mdFile = path.join(folder, `${symbol}-Report-${timestamp}.md`);
    if (options.report || (!options.excel && !options.docx)) {
      fs.writeFileSync(mdFile, mdContent, 'utf-8');
    }

    // Excel
    let excelFile = '';
    if (options.excel) {
      const wb = new ExcelJS.Workbook();
      const ws = wb.addWorksheet(`${symbol} Summary`);
      ws.columns = [
        { header: 'Metric', key: 'metric', width: 25 },
        { header: 'Value', key: 'value', width: 25 }
      ];
      ws.addRows([
        { metric: 'Symbol', value: symbol },
        { metric: 'Name', value: companyName },
        { metric: 'Price', value: `${curPrice} ${currency}` },
        { metric: '52 Week High', value: quote.fiftyTwoWeekHigh },
        { metric: '52 Week Low', value: quote.fiftyTwoWeekLow },
        { metric: 'Volume', value: quote.regularMarketVolume },
        { metric: 'Market Cap', value: quote.marketCap },
      ]);
      excelFile = path.join(folder, `${symbol}-Data-${timestamp}.xlsx`);
      await wb.xlsx.writeFile(excelFile);
    }

    // DOCX
    let docxFile = '';
    if (options.docx || options.report) {
      const doc = new Document({
        creator: 'Scrappy',
        title: `${symbol} Report`,
        sections: [{
          properties: {},
          children: [
            new Paragraph({ children: [new TextRun({ text: `Stock Report: ${companyName} (${symbol})`, bold: true, size: 36 })], heading: HeadingLevel.TITLE, alignment: AlignmentType.CENTER, spacing: { after: 300 } }),
            new Paragraph({ text: `Price: ${curPrice} ${currency} | Market Cap: ${quote.marketCap ?? 'N/A'}`, spacing: { after: 200 } }),
            new Paragraph({ children: [new TextRun({ text: 'Executive Summary', bold: true, size: 28 })], heading: HeadingLevel.HEADING_1, spacing: { before: 200, after: 100 } }),
            new Paragraph({ text: analysisSummary, spacing: { after: 200 } }),
            new Paragraph({ children: [new TextRun({ text: 'Key Takeaways', bold: true, size: 28 })], heading: HeadingLevel.HEADING_1, spacing: { before: 200, after: 100 } }),
            ...analysisTakeaways.map(t => new Paragraph({ text: `- ${t}`, spacing: { after: 100 } })),
          ],
        }],
      });
      docxFile = path.join(folder, `${symbol}-Report-${timestamp}.docx`);
      const buffer = await Packer.toBuffer(doc);
      fs.writeFileSync(docxFile, buffer);
    }

    await progress('Completed', 100);
    console.log(c.blue('║') + '─'.repeat(getLayoutWidth() - 2) + c.blue('║'));
    printResponseLine(c.blueBold('📁 Generated Files:'));
    if (options.report || (!options.excel && !options.docx)) {
      printResponseLine(c.green('  ✓ ') + c.white('Markdown : ') + c.gray(mdFile));
    }
    if (docxFile) {
      printResponseLine(c.green('  ✓ ') + c.white('Word Doc : ') + c.gray(docxFile));
    }
    if (excelFile) {
      printResponseLine(c.green('  ✓ ') + c.white('Excel    : ') + c.gray(excelFile));
    }
    printDivider();
    printResponseLine(c.blue('  📊 RESEARCH COMPLETE') + c.gray(` — ${news.news.length} sources analysed`));
    printDivider();
    
    endResponse();

  } catch (err: any) {
    console.log();
    console.error(c.red(`  ✗ Stock fetch failed: ${err.message}`));
  }
}
